# Generated by Django 4.0 on 2021-12-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetofinal',
            name='Busca',
            field=models.TextField(),
        ),
    ]
